"""Rule definitions and text normalization for transaction classification."""

from __future__ import annotations

import re

# Fixed label space used in thesis experiments.
CATEGORIES: list[str] = [
    "Groceries",
    "Eating Out",
    "Housing & Insurance",
    "Bills & Utilities",
    "Transport & Travel",
    "Health",
    "Entertainment & Leisure",
    "Shopping",
    "Income & Savings",
    "Other",
]

# Grouped keyword rules (group -> keywords) used in thesis notebook experiments.
RULES: dict[str, list[str]] = {
    "Groceries": [
        "WINMART",
        "COOPMART",
        "AEON",
        "LOTTE",
        "LIDL",
        "TESCO",
        "SAINSBURYS",
        "ASDA",
        "MORRISONS",
        "WAITROSE",
        "COOP",
        "GROCERY",
        "ORIENTAL",
        "GHOUSIA",
        "POUNDLAND",
        "BARRETT",
        "FOOD",
    ],
    "Eating Out": [
        "PHO",
        "COM TAM",
        "HIGHLANDS",
        "PHUC LONG",
        "KFC",
        "LOTTERIA",
        "JOLLIBEE",
        "STARBUCKS",
        "SUBWAY",
        "GREGGS",
        "NERO",
        "RESTAURANT",
        "CAFE",
        "ATRIUM",
        "BRONTOSAURUS",
        "VEGAN",
        "DESSERT",
        "DOUGHNOTTS",
        "DELIVEROO",
        "PIZZA",
        "BAKERY",
        "LOUNGE",
        "COSTA",
        "PRET",
        "MCDONALD",
        "DOMINOS",
    ],
    "Housing & Insurance": [
        "RENT",
        "INSURANCE",
        "MORTGAGE",
        "BAO VIET",
        "PRUDENTIAL",
        "MANULIFE",
        "AVIVA",
        "ZURICH",
        "ASSURANT",
        "NATWEST",
        "SANTANDER",
        "PRINCIPALITY",
    ],
    "Bills & Utilities": [
        "EVN",
        "VNPT",
        "FPT",
        "VIETTEL",
        "ENERGY",
        "WATER",
        "ELECTRIC",
        "VIRGIN",
        "TALKTALK",
        "COUNCIL",
        "TAX",
        "DWR",
        "CYMRU",
        "NON GBP",
        "PURCH FEE",
        "TRANS FEE",
    ],
    "Transport & Travel": [
        "PETROL",
        "PETROLIMEX",
        "PVOIL",
        "GRAB",
        "BE",
        "UBER",
        "VIETJET",
        "AIRLINES",
        "RAIL",
        "TRAIN",
        "TRAINS",
        "ARRIVA",
        "GWR",
        "EASYJET",
        "KLM",
        "EXPEDIA",
        "HOTEL",
        "TRAVELIUM",
    ],
    "Health": [
        "VINMEC",
        "PHARMACITY",
        "LONG CHAU",
        "HOSPITAL",
        "CLINIC",
    ],
    "Entertainment & Leisure": [
        "NETFLIX",
        "SPOTIFY",
        "CGV",
        "CINEMA",
        "STEAM",
        "YOUTUBE",
        "GYM",
        "FITNESS",
        "AUDIBLE",
        "CINEWORLD",
    ],
    "Shopping": [
        "AMAZON",
        "AMZN",
        "MARKETPL",
        "SHOPEE",
        "LAZADA",
        "TIKI",
        "UNIQLO",
        "ZARA",
        "EBAY",
        "ARGOS",
        "MARKS",
        "SPENCER",
        "WILKO",
        "RETAIL",
        "IKEA",
        "MAXX",
        "HPI",
        "INK",
        "NEXT",
        "JD",
        "BOOTS",
        "CURRYS",
        "PRIMARK",
    ],
    "Income & Savings": [
        "PAYROLL",
        "SALARY",
        "WAGE",
        "TRANSFER",
        "INTEREST",
        "SAVINGS",
        "SAVE",
        "CHANGE",
        "TRADING212UK",
        "LLOYDS",
        "UNIVERSITY",
        "PAY",
        "UNIV",
        "NOTTINGHAM",
        "III",
        "IISL",
        "CLIENT",
        "DIVIDEND",
        "REFUND",
        "CASHBACK",
        "WAIVED",
    ],
    "Other": ["ATM", "CASH"],
}

# Token weights for hybrid weighted rule score; default must be 1.
RULE_WEIGHTS: dict[str, float] = {
    "AMAZON": 3,
    "AMZN": 3,
    "LIDL": 3,
    "TESCO": 3,
    "SAINSBURYS": 3,
    "UBER": 2,
    "ARRIVA": 2,
    "VIRGIN": 2,
    "PAYROLL": 3,
    "SALARY": 3,
    "TRADING212UK": 3,
}

RULE_WEIGHTS.update(
    {
        "BRONTOSAURUS": 2,
        "DELIVEROO": 2,
        "UNIV": 2,
        "III": 3,
        "IISL": 3,
        "IKEA": 2,
        "ORIENTAL": 2,
    }
)

DEFAULT_CATEGORY = "Other"


def normalize(text: str) -> str:
    """Normalize transaction text exactly as defined in the research notebook."""
    text = str(text).upper()
    text = re.sub(r"[^A-Z0-9 ]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text
